
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(PU+868DKCkBB2ltWNHDIcA==)
    password: ENC(BW2rUWsVflKabBLnOtlAvt1xlgmJleyC)
    url: jdbc:mysql://127.0.0.1:3306/parkingtest?characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 127.0.0.1  #配置redis的主机地址，需要修改成自己的
    database: 5
    port: 6379
    password: #设置自己的密码
    jedis:
      pool:
        max-active: 50 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool 的状态为exhausted(耗尽)
        max-idle: 20 # 连接池中的最大空闲连接，默认值也是8。
        min-idle: 5  # 连接池中的最小空闲连接，默认值也是0。       # max-wait: 5 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接 抛出JedisConnectionException
  aop:
    proxy-target-class: true        #默认为false
    auto: true        #默认为
server:
  port: 8080
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: XyO8frEh0i4dX14S


