
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: glx000630
    url: jdbc:mysql://127.0.0.1:3306/parkingtest?characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


